version: 2

models:
  - name: STREAM_NAME_TEST
    description: Test table

    columns:
      - name: test_column
        tests:
          - unique
          - not_null

      - name: id
        description: test id
