version: 2

models:
  - name: operations
    description: Test table
    columns:
      - name: test_column
        tests:
          - unique
          - not_null

      - name: id
        description: test id
